### ISSUE TITLE
EEPROM registers address

### ISSUE THREAD

**Issue by pcremades** [adafruit/Adafruit-MLX90614-Library#11]
Dear developer,
I think there is an error in the EEPROM registes address definitions. According to the MLX90614 datasheet:
TOmax   0x00
TOmin    0x01
PWMCRTL  0x02
Ta_range 0x03
EmissCoef 0x04
ConfigReg 0x05

But in the Header file of the library these are defined as
TOmax   0x20
TOmin    0x21
PWMCRTL  0x22
Ta_range 0x23
EmissCoef 0x24
ConfigReg 0x25

Am I missing something?

**Comment by ladyada** [comment]
![image](https://user-images.githubusercontent.com/1214161/80288234-b4bb1580-8704-11ea-8a9f-82d3213969d7.png)

**Comment by ladyada** [comment]
see datasheet for explaination

**Comment by danial2016** [comment]
Ye, the datasheet was a bit misguiding concerning the EEPROM register addresses. But do the following to get the real EEPROM address (virtually adding 2 in the upper nibble):
0b0010_0000+ 0b000x_xxxx = 0b001x_xxxx where x_xxxx is the EEPROM reg address at the page OP refers to.

**Comment by ladyada** [comment]
its been a long time since we tried this chip, if you can submit a PR indicating the changes to use the EEPROM we'll take a look :)
