### ISSUE TITLE
Using different I2C buses

### ISSUE THREAD

**Issue by mhmayyan** [adafruit/Adafruit-MLX90614-Library#14]
This is not an issue reporting. I just wanted to suggest a small modification that allows using other I2C buses. 

.h modifications:-
Adafruit_MLX90614(TwoWire *I2C= &Wire, uint8_t addr = MLX90614_I2CADDR);
private:
TwoWire *_Wire;

.cpp modifications:-
Adafruit_MLX90614::Adafruit_MLX90614(TwoWire *I2C, uint8_t i2caddr) { _Wire = I2C; _addr = i2caddr; }
Then change every "Wire." to "_Wire->"

Thanks,

**Comment by fervidautomation** [comment]
I have done the below changes to use the two wire in MLX and I got below error.

Arduino: 1.8.13 (Windows 10), Board: "ESP32 Wrover Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), QIO, 80MHz, 921600, None"

C:\shared\ESP32_MAX30102_simple-SpO2_plotter-master\ESP32_MAX30102_simple-SpO2_plotter\ESP32_MAX30102_simple-SpO2_plotter.ino: In function 'void setup()':

ESP32_MAX30102_simple-SpO2_plotter:97:37: error: no matching function for call to 'Adafruit_MLX90614::Adafruit_MLX90614(TwoWire&, int)'

  mlx = Adafruit_MLX90614(I2CBME,0x5A);

                                     ^

In file included from C:\shared\ESP32_MAX30102_simple-SpO2_plotter-master\ESP32_MAX30102_simple-SpO2_plotter\ESP32_MAX30102_simple-SpO2_plotter.ino:72:0:

C:\Users\techs\OneDrive\Documents\Arduino\libraries\Adafruit_MLX90614_Library/Adafruit_MLX90614.h:52:5: note: candidate: Adafruit_MLX90614::Adafruit_MLX90614(TwoWire*, uint8_t)

     Adafruit_MLX90614(TwoWire *I2C= &Wire, uint8_t addr = MLX90614_I2CADDR);

     ^

C:\Users\techs\OneDrive\Documents\Arduino\libraries\Adafruit_MLX90614_Library/Adafruit_MLX90614.h:52:5: note:   no known conversion for argument 1 from 'TwoWire' to 'TwoWire*'

C:\Users\techs\OneDrive\Documents\Arduino\libraries\Adafruit_MLX90614_Library/Adafruit_MLX90614.h:50:7: note: candidate: constexpr Adafruit_MLX90614::Adafruit_MLX90614(const Adafruit_MLX90614&)

 class Adafruit_MLX90614 {

       ^

C:\Users\techs\OneDrive\Documents\Arduino\libraries\Adafruit_MLX90614_Library/Adafruit_MLX90614.h:50:7: note:   candidate expects 1 argument, 2 provided

C:\Users\techs\OneDrive\Documents\Arduino\libraries\Adafruit_MLX90614_Library/Adafruit_MLX90614.h:50:7: note: candidate: constexpr Adafruit_MLX90614::Adafruit_MLX90614(Adafruit_MLX90614&&)

C:\Users\techs\OneDrive\Documents\Arduino\libraries\Adafruit_MLX90614_Library/Adafruit_MLX90614.h:50:7: note:   candidate expects 1 argument, 2 provided

exit status 1

no matching function for call to 'Adafruit_MLX90614::Adafruit_MLX90614(TwoWire&, int)'



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.


Adafruit_MLX90614(TwoWire *I2C= &Wire, uint8_t addr = MLX90614_I2CADDR);
  TwoWire *_Wire;

Adafruit_MLX90614::Adafruit_MLX90614(TwoWire *I2C, uint8_t i2caddr) { _Wire = I2C; _addr = i2caddr; }




#include <Wire.h>
#include <MAX30105.h> //sparkfun MAX3010X library
#include <Adafruit_MLX90614.h>

  bool status; 
Adafruit_MLX90614 mlx;
MAX30105 particleSensor;
TwoWire I2CBME = TwoWire(0);
 TwoWire I2CMLX = TwoWire(1);

//#define MAX30105 //if you have Sparkfun's MAX30105 breakout board , try #define MAX30105 

#define USEFIFO
#define I2C_SDA 33  //21
#define I2C_SCL 32  //22

#define I2C_SDA1 21  //21
#define I2C_SCL1 22  //2



void setup()
{
  Serial.begin(9600);
 I2CMLX.begin(I2C_SDA1, I2C_SCL1, I2C_SPEED_FAST);
 
   I2CBME.begin(I2C_SDA, I2C_SCL, I2C_SPEED_FAST);
 mlx = Adafruit_MLX90614(I2CBME,0x5A);
   mlx.begin();
 // Serial.println("mlx start Initializing...");

//status = mlx.begin();  
  Serial.print("mlx status is " + status) ;
 // mlx.begin();
 
//   if (!mlx.begin()) //Use default I2C port, 400kHz speed
//  {
//     Serial.println("mlx was not found. . ");
//      while (1);
//  }

 // Serial.println("max start Initializing...") ;

  // Initialize sensor
  //if (!particleSensor.begin(Wire, I2C_SPEED_FAST)) //Use default I2C port, 400kHz speed
  if (!particleSensor.begin(I2CBME, I2C_SPEED_FAST ,0x57)) //Use default I2C port, 400kHz speed
  {
    Serial.println("MAX30102 was not found. Please check wiring/power/solder jumper at MH-ET LIVE MAX30102 board. ");
    while (1);
  }

  //Setup to sense a nice looking saw tooth on the plotter
  byte ledBrightness = 0x7F; //Options: 0=Off to 255=50mA
  byte sampleAverage = 4; //Options: 1, 2, 4, 8, 16, 32
  byte ledMode = 2; //Options: 1 = Red only, 2 = Red + IR, 3 = Red + IR + Green
  //Options: 1 = IR only, 2 = Red + IR on MH-ET LIVE MAX30102 board
  int sampleRate = 200; //Options: 50, 100, 200, 400, 800, 1000, 1600, 3200
  int pulseWidth = 411; //Options: 69, 118, 215, 411
  int adcRange = 16384; //Options: 2048, 4096, 8192, 16384
  // Set up the wanted parameters
  particleSensor.setup(ledBrightness, sampleAverage, ledMode, sampleRate, pulseWidth, adcRange); //Configure sensor with these settings
}
double avered = 0; double aveir = 0;
double sumirrms = 0;
double sumredrms = 0;
int i = 0;
int Num = 100;//calculate SpO2 by this sampling interval

double ESpO2 = 95.0;//initial value of estimated SpO2
double FSpO2 = 0.7; //filter factor for estimated SpO2
double frate = 0.95; //low pass filter for IR/red LED value to eliminate AC component
#define TIMETOBOOT 3000 // wait for this time(msec) to output SpO2
#define SCALE 88.0 //adjust to display heart beat and SpO2 in the same scale
#define SAMPLING 5 //if you want to see heart beat more precisely , set SAMPLING to 1
#define FINGER_ON 30000 // if red signal is lower than this , it indicates your finger is not on the sensor
#define MINIMUM_SPO2 80.0

void loop()
{
Serial.print("status is mlx " + status) ;
        Serial.println("Ambient = ");
Serial.print(mlx.readAmbientTempC());
Serial.print("*C\tObject = ");
Serial.print(mlx.readObjectTempC());
Serial.println("*C");
Serial.print("Ambient = ");
Serial.print(mlx.readAmbientTempF());
Serial.print("*F\tObject = ");
Serial.print(mlx.readObjectTempF());
Serial.println("*F");

delay(5000);
  uint32_t ir, red , green;
  double fred, fir;
  double SpO2 = 0; //raw SpO2 before low pass filtered

#ifdef USEFIFO
  particleSensor.check(); //Check the sensor, read up to 3 samples

  while (particleSensor.available()) {//do we have new data
#ifdef MAX30105
   red = particleSensor.getFIFORed(); //Sparkfun's MAX30105
    ir = particleSensor.getFIFOIR();  //Sparkfun's MAX30105
#else
    red = particleSensor.getFIFOIR(); //why getFOFOIR output Red data by MAX30102 on MH-ET LIVE breakout board
    ir = particleSensor.getFIFORed(); //why getFIFORed output IR data by MAX30102 on MH-ET LIVE breakout board
#endif
    i++;

 


    
    fred = (double)red;
    fir = (double)ir;
    avered = avered * frate + (double)red * (1.0 - frate);//average red level by low pass filter
    aveir = aveir * frate + (double)ir * (1.0 - frate); //average IR level by low pass filter
    sumredrms += (fred - avered) * (fred - avered); //square sum of alternate component of red level
    sumirrms += (fir - aveir) * (fir - aveir);//square sum of alternate component of IR level
    if ((i % SAMPLING) == 0) {//slow down graph plotting speed for arduino Serial plotter by thin out
      if ( millis() > TIMETOBOOT) {
        float ir_forGraph = (2.0 * fir - aveir) / aveir * SCALE;
        float red_forGraph = (2.0 * fred - avered) / avered * SCALE;
        //trancation for Serial plotter's autoscaling
        if ( ir_forGraph > 100.0) ir_forGraph = 100.0;
        if ( ir_forGraph < 80.0) ir_forGraph = 80.0;
        if ( red_forGraph > 100.0 ) red_forGraph = 100.0;
        if ( red_forGraph < 80.0 ) red_forGraph = 80.0;
        //        Serial.print(red); Serial.print(","); Serial.print(ir);Serial.print(".");
        if (ir < FINGER_ON) ESpO2 = MINIMUM_SPO2; //indicator for finger detached
        Serial.print(ir_forGraph); // to display pulse wave at the same time with SpO2 data
        Serial.print(","); Serial.print(red_forGraph); // to display pulse wave at the same time with SpO2 data
        Serial.print(",");
        Serial.print(ESpO2); //low pass filtered SpO2
        Serial.print(","); Serial.print(85.0); //reference SpO2 line
        Serial.print(","); Serial.print(90.0); //warning SpO2 line
        Serial.print(","); Serial.print(95.0); //safe SpO2 line
        Serial.print(","); Serial.println(100.0); //max SpO2 line
        delay(3000);


      }
    }
    if ((i % Num) == 0) {
      double R = (sqrt(sumredrms) / avered) / (sqrt(sumirrms) / aveir);
      // Serial.println(R);
      SpO2 = -23.3 * (R - 0.4) + 100; //http://ww1.microchip.com/downloads/jp/AppNotes/00001525B_JP.pdf
      ESpO2 = FSpO2 * ESpO2 + (1.0 - FSpO2) * SpO2;//low pass filter
      //  Serial.print(SpO2);Serial.print(",");Serial.println(ESpO2);
      sumredrms = 0.0; sumirrms = 0.0; i = 0;
      break;
    }
    particleSensor.nextSample(); //We're finished with this sample so move to next sample
    //Serial.println(SpO2);
  }
#else

  while (1) {//do we have new data
#ifdef MAX30105
   red = particleSensor.getRed();  //Sparkfun's MAX30105
    ir = particleSensor.getIR();  //Sparkfun's MAX30105
#else
    red = particleSensor.getIR(); //why getFOFOIR outputs Red data by MAX30102 on MH-ET LIVE breakout board
    ir = particleSensor.getRed(); //why getFIFORed outputs IR data by MAX30102 on MH-ET LIVE breakout board
#endif
    i++;
    fred = (double)red;
    fir = (double)ir;
    avered = avered * frate + (double)red * (1.0 - frate);//average red level by low pass filter
    aveir = aveir * frate + (double)ir * (1.0 - frate); //average IR level by low pass filter
    sumredrms += (fred - avered) * (fred - avered); //square sum of alternate component of red level
    sumirrms += (fir - aveir) * (fir - aveir);//square sum of alternate component of IR level
    if ((i % SAMPLING) == 0) {//slow down graph plotting speed for arduino IDE toos menu by thin out
      //#if 0
      if ( millis() > TIMETOBOOT) {
        float ir_forGraph = (2.0 * fir - aveir) / aveir * SCALE;
        float red_forGraph = (2.0 * fred - avered) / avered * SCALE;
        //trancation for Serial plotter's autoscaling
        if ( ir_forGraph > 100.0) ir_forGraph = 100.0;
        if ( ir_forGraph < 80.0) ir_forGraph = 80.0;
        if ( red_forGraph > 100.0 ) red_forGraph = 100.0;
        if ( red_forGraph < 80.0 ) red_forGraph = 80.0;
        //        Serial.print(red); Serial.print(","); Serial.print(ir);Serial.print(".");
        if (ir < FINGER_ON) ESpO2 = MINIMUM_SPO2; //indicator for finger detached
        Serial.print((2.0 * fir - aveir) / aveir * SCALE); // to display pulse wave at the same time with SpO2 data
        Serial.print(","); Serial.print((2.0 * fred - avered) / avered * SCALE); // to display pulse wave at the same time with SpO2 data
        Serial.print(","); Serial.print(ESpO2); //low pass filtered SpO2
        Serial.print(","); Serial.print(85.0); //
        Serial.print(","); Serial.print(90.0); //warning SpO2 line
        Serial.print(","); Serial.print(95.0); //safe SpO2 line
        Serial.print(","); Serial.println(100.0); //max SpO2 line
        //#endif

 
Serial.println();
delay(1000);

      }
    }
    if ((i % Num) == 0) {
      double R = (sqrt(sumredrms) / avered) / (sqrt(sumirrms) / aveir);
      // Serial.println(R);
      SpO2 = -23.3 * (R - 0.4) + 100; //http://ww1.microchip.com/downloads/jp/AppNotes/00001525B_JP.pdf
      ESpO2 = FSpO2 * ESpO2 + (1.0 - FSpO2) * SpO2;
      //  Serial.print(SpO2);Serial.print(",");Serial.println(ESpO2);
      sumredrms = 0.0; sumirrms = 0.0; i = 0;
      break;
    }
    particleSensor.nextSample(); //We're finished with this sample so move to next sample
    //Serial.println(SpO2);
  }
#endif
}
