### ISSUE TITLE
Why is the MLX90614 Datasheet Measurement Resolution 0.02 C but in after I try, it can be 0.01 C?

### ISSUE THREAD

**Issue by jake-winson** [adafruit/Adafruit-MLX90614-Library#21]
I thought I would get even data, but it turns out I can get odd data too.

how it can be happened?

**Comment by jake-winson** [comment]
I couldn't provide my example, but here's the example from internet 
![image](https://user-images.githubusercontent.com/76038724/102193205-60141700-3eee-11eb-9e1a-2a314216c7fb.png)

**Comment by jake-winson** [comment]
I couldn't provide my example, but here's the example from internet 
![image](https://user-images.githubusercontent.com/76038724/102194830-57bcdb80-3ef0-11eb-82c1-bb915f5a28fd.png)

on the last data, the object is 27.16 degree C

**Comment by ladyada** [comment]
rounding effect and floating point inconsistancies!
https://github.com/adafruit/Adafruit-MLX90614-Library/blob/master/Adafruit_MLX90614.cpp#L117
https://floating-point-gui.de/
