### ISSUE TITLE
how to read and set the MLX90614's emissivity coefficient

### ISSUE THREAD

**Issue by ilhmfahmi** [adafruit/Adafruit-MLX90614-Library#22]
i tried to make diy thermometer for non contact temperature measurements using mlx 90614, but it doesnt look very good when sensing human body its around 32C/33C. how to set the MLX90614's emissivity coefficient?
thanks.

**Comment by caternuson** [comment]
To read use:
http://adafruit.github.io/Adafruit-MLX90614-Library/html/class_adafruit___m_l_x90614.html#ab261e8d7caeb72a419524cee1a7641b3
To write use:
http://adafruit.github.io/Adafruit-MLX90614-Library/html/class_adafruit___m_l_x90614.html#a26477cd34fbdfc259102ec989a62d0f2
