### ISSUE TITLE
Connections for the device seem to be missing

### ISSUE THREAD

**Issue by jkwilborn** [adafruit/Adafruit-MLX90614-Library#4]
Hello, I've used this library before and remember having to chase down the connections to the 'two wire' interface.  It would be nice if you put the actual pin numbers in the source, as the phrase "These sensors use I2C to communicate, 2 pins are required to interface."  If you don't say which pin goes where.  I can figure out the ground and power parts..  It's the SDA and SCL pins.  I also have a 5v device, I'm glad you mentioned this in your source (you did, didn't you?) 

I had this problem before and modified my source to reflect the actual pin connections to the device.  Now working on a similar system, I wanted to check some things... Now I'm chasing pin connections again.

Thanks for the code, it's handy especially for learning about new devices.

Sorry to bother you, but I though it better to advise you.  Handle it any way you feel is right.

Thanks
Jack Wilborn
Peoria, Arizona

**Comment by ladyada** [comment]
https://learn.adafruit.com/using-melexis-mlx90614-non-contact-sensors/overview
