### ISSUE TITLE
The MLX90614 reports widely incorrect data after setting emissivity

### ISSUE THREAD

**Issue by TheStranger25** [adafruit/Adafruit-MLX90614-Library#43]
Hello everyone, I am using this library to use a MLX90614 on ESP8266.

For a couple of days I’ve been trying to solve a problem that involves setting emissivity dynamically.
I have already read the closed issue #32 in which it is explained that doing it dynamically is not very reliable but in my case it is essential. 
I tried various ways like: reset the card after setting the emissivity in a zone that is not the Setup() or tried to call the function SetEmissivityReg setting the register 0x04 to 0 as per manual (which makes no sense as it is already done in the SetEmissivity() library). 

Here is the problem described step by step:
- I run mlx.begin() in the setup and also imposed the emissivity that had been saved to a file;
- Data starts to be read correctly (Sometimes not, but is described later);
- Change of emissivity according to user wishes
- The values read now are about 600 for the environment and -147 for the object (may vary slightly)
- At this point if I restart the card it may happen that it adjusts or that the values remain wrong

Here are some:
![image](https://github.com/adafruit/Adafruit-MLX90614-Library/assets/104565485/1b7fd560-aad4-4974-bd10-c725133296ba)
![image](https://github.com/adafruit/Adafruit-MLX90614-Library/assets/104565485/0180e2a5-4c84-456b-bf2d-9dfc0d80f4f3)

**Comment by caternuson** [comment]
This support will need to be taken care of in user code. As discussed in the other issue thread linked above, the MLX requires a power cycle after setting emissivity.

You'd need to do something like the other poster did:

> For an immediate countermeasure, I am tying the MLX90614 GND pin to a digital output pin D4 on my MCU. After writing the emissivity, I raise D4 high, wait 50ms, and lower D4 again.

However, this library generally is not setup to handle power cycles. So you may also need to reinitialize sensor state after the power cycle.

**Comment by TheStranger25** [comment]
I also tried to raise the pin D4 (2) to which the mass is connected, wait 100ms and then lower it again but this did not work. 
It didn’t even work by adding an ESP.Reset();
Turning off the power completely can work but not always, sometimes you have to do it several times, not very reliable.

**Comment by TheStranger25** [comment]
So...which is the solution?

**Comment by caternuson** [comment]
```
Turning off the power completely can work but not always, sometimes you have to do it several times, not very reliable.
```
What is the behavior when it does not work? How do you know when it finally works?

```
How should I reinitialize sensor state after the power cycle.
```
Depends on what all gets power cycled. If it's just the MLX, maybe no need to reinitialize. Just start querying data from it again.

**Comment by TheStranger25** [comment]
`What is the behavior when it does not work? How do you know when it finally works?`
When it doesn't work anymore I notice it because the ambient temperature exceeds 600 degrees while that of the object goes below -140 degrees, while when it works the temperatures are around 25 degrees

**Comment by TheStranger25** [comment]
I found a method to avoid setting the emissivity several times and the following adjustments were necessary:
- first of all I set it only in my configuration webserver
- I avoid setting it in the setup as it could "break" every time it is turned on again
- if I set it through the webserver I created, I have to remove and reconnect the power (just restarting the card from the esp is not enough)
